#include "ui/SettingsWindow.h"

#include <QDir>
#include <QEvent>
#include <QGuiApplication>
#include <QKeyEvent>
#include <QPropertyAnimation>
#include <QQmlComponent>
#include <QQmlEngine>
#include <QQuickItem>
#include <QQuickWindow>
#include <QScreen>
#include <QTimer>

#include "core/AutostartManager.h"
#include "core/HotkeyManager.h"
#include "core/ScanService.h"
#include "core/SettingsStore.h"
#include "core/UpdateService.h"
#include "ui/HotkeyCaptureDialog.h"

namespace {

// D-02: click-away grace (launcher's D-02.4 pattern) and the UI-SPEC
// 120ms open fade (Theme.animFade).
constexpr int kGraceMs = 150;
constexpr int kFadeMs = 120;

} // namespace

SettingsWindow::SettingsWindow(QQmlEngine *engine, SettingsStore *settingsStore,
                               AutostartManager *autostart, HotkeyManager *hotkeys,
                               HotkeyCaptureDialog *capture, ScanService *scanService,
                               UpdateService *updates, QObject *parent)
    : QObject(parent)
    , m_engine(engine)
    , m_settingsStore(settingsStore)
    , m_autostart(autostart)
    , m_hotkeys(hotkeys)
    , m_capture(capture)
    , m_scanService(scanService)
    , m_updates(updates)
{
    // Hotkey-row handoff (D-03, success criterion 3): the EXISTING capture
    // dialog validates (F12/mod-only rejected) and surfaces conflicts via its
    // shipped balloon path — the controller only re-registers on accept.
    // setHotkey persists + atomically swaps (HOTK-01); on OS conflict the old
    // combo stays registered and registrationFailed fires (never silent).
    connect(m_capture, &HotkeyCaptureDialog::accepted, this,
            [this](const QString &seq) {
                m_hotkeys->setHotkey(QKeySequence(seq));
                emit currentHotkeyChanged(); // live well text (QML binding)
            });

    // 07-05: the last-scan summary follows scans LIVE while the window is
    // open - the QML binding stays fresh without polling.
    if (m_scanService) {
        connect(m_scanService, &ScanService::scanStateChanged, this,
                [this] { emit lastScanSummaryChanged(); });
    }

    // Phase 8: every engine transition recomposes the inline status line
    // (UI-SPEC S1 states; D-10 - failures are text here, never popups).
    if (m_updates) {
        connect(m_updates, &UpdateService::stateChanged, this,
                [this] { emit updateStatusChanged(); });
    }

    m_graceTimer = new QTimer(this);
    m_graceTimer->setSingleShot(true);
    m_graceTimer->setInterval(kGraceMs);
    connect(m_graceTimer, &QTimer::timeout, this, &SettingsWindow::onGraceTimeout);
}

void SettingsWindow::open()
{
    QQuickWindow *win = ensureWindow();
    if (!win)
        return;

    // D-10: state is read when settings opens (and after every mutation).
    emit autostartEnabledChanged();
    emit currentHotkeyChanged();
    refreshScanState();

    // UI-SPEC open sequence: center → fade-in (120ms) → requestActivate.
    centerOnPrimary(win);
    win->setOpacity(0.0);
    if (m_closeFade)
        m_closeFade->stop(); // re-open mid-close-fade: start fresh from 0
    win->show();
    if (m_fade)
        m_fade->start();
    win->requestActivate();
    // First focus on the hotkey row = first Tab stop (UI-SPEC Interaction
    // Contract + Keyboard row: hotkey well → strip → Custom… → toggle).
    if (QQuickItem *content = win->contentItem())
        content->forceActiveFocus();
    emit settingsVisibleChanged(true);
}

void SettingsWindow::close()
{
    m_graceTimer->stop();
    m_hasBeenActive = false; // the next open re-arms the grace on ITS first activation
    if (m_fade)
        m_fade->stop();
    if (m_window && m_window->isVisible()) {
        // 2026-08-15: fade-out on close — the mirror of the open fade (same
        // 120ms token, Theme.animFade). Animate opacity → 0, then hide. The
        // open fade is stopped first so the two animations never race.
        if (m_closeFade)
            m_closeFade->start();
    } else {
        hideWindow();
    }
}

void SettingsWindow::hideWindow()
{
    if (!m_window)
        return;
    m_window->setOpacity(1.0); // reset — the next open fades from 0 again
    m_window->hide();
    emit settingsVisibleChanged(false);
}

QString SettingsWindow::currentHotkey() const
{
    return m_hotkeys ? m_hotkeys->hotkey().toString() : QString();
}

bool SettingsWindow::autostartEnabled() const
{
    return m_autostart && m_autostart->isEnabled();
}

void SettingsWindow::applyAccent(const QColor &c)
{
    // D-06 path: persist + live apply. Invalid colors are silently ignored
    // downstream (SettingsStore, D-16).
    if (m_settingsStore)
        m_settingsStore->setAccent(c);
}

void SettingsWindow::commitCustomColor(const QString &hex)
{
    // T-06-01: the hex string is GENERATED by the staged dialog (never
    // freeform input); an invalid value is silently ignored (D-16).
    QColor c;
    c.setNamedColor(hex);
    if (!c.isValid())
        return;
    applyAccent(c);
}

void SettingsWindow::toggleAutostart()
{
    if (!m_autostart)
        return;
    m_autostart->setEnabled(!m_autostart->isEnabled());
    // The toggle reflects the operation's OUTCOME (UI-SPEC): the property
    // getter reads the store live, so a failed write stays visually off.
    emit autostartEnabledChanged();
}

QStringList SettingsWindow::scanRoots() const
{
    return m_settingsStore ? m_settingsStore->scanRoots() : QStringList();
}

int SettingsWindow::scanIntervalMinutes() const
{
    return m_settingsStore ? m_settingsStore->scanIntervalMinutes() : 10;
}

QString SettingsWindow::lastScanSummary() const
{
    return m_scanService ? m_scanService->lastScanSummary() : QString();
}

bool SettingsWindow::scanning() const
{
    return m_scanService
        && m_scanService->stateOrdinal() == int(ScanService::ScanState::Scanning);
}

void SettingsWindow::addScanRoot()
{
    if (!m_settingsStore || !m_folderPicker)
        return; // picker seam not wired → treat as cancelled
    // D-05: roots come ONLY from the native folder picker — no free-text
    // paths, no wildcards (T-07-04).
    const QString dir = m_folderPicker();
    if (dir.isEmpty())
        return; // cancelled → nothing (D-11 cancel discipline)
    QStringList roots = m_settingsStore->scanRoots();
    if (roots.contains(QDir::toNativeSeparators(dir)))
        return; // duplicate root → no-op (T-07-04)
    roots.append(dir); // normalized inside setScanRoots (Pitfall 5)
    m_settingsStore->setScanRoots(roots);
    emit scanRootsChanged();
    if (m_scanService)
        m_scanService->requestScan(); // D-09: first scan after roots are added
}

void SettingsWindow::removeScanRoot(int index)
{
    if (!m_settingsStore)
        return;
    QStringList roots = m_settingsStore->scanRoots();
    if (index < 0 || index >= roots.size())
        return; // guard — never touch an out-of-range index
    roots.removeAt(index);
    m_settingsStore->setScanRoots(roots);
    emit scanRootsChanged();
    if (m_scanService)
        m_scanService->requestScan(); // empty roots → walkAndDelta wipes → NoRoots
}

void SettingsWindow::setScanInterval(int minutes)
{
    if (!m_settingsStore)
        return;
    m_settingsStore->setScanIntervalMinutes(minutes); // clamp lives here (OQ4)
    emit scanIntervalChanged();
    if (m_scanService)
        m_scanService->refreshInterval(); // re-arm the timer from a fresh snapshot
}

void SettingsWindow::scanNow()
{
    if (m_scanService)
        m_scanService->requestScan(); // single-flight gate inside (07-03)
}

// ── Updates section (Phase 8, UI-SPEC S1) ─────────────────────────────

QString SettingsWindow::updateStatus() const
{
    // Composed LIVE from engine state - the single source of the inline
    // status text (D-10). Copy per UI-SPEC S1 states.
    if (!m_updates)
        return QStringLiteral("Not checked yet");
    switch (m_updates->state()) {
    case UpdateService::State::Idle:
        return QStringLiteral("Not checked yet");
    case UpdateService::State::Checking:
        return QStringLiteral("Checking...");
    case UpdateService::State::UpToDate:
        return QStringLiteral("You're up to date");
    case UpdateService::State::Available: {
        const QString v = m_updates->availableVersion();
        return v.isEmpty() ? QStringLiteral("Update available")
                           : QStringLiteral("Update to v%1 available").arg(v);
    }
    case UpdateService::State::CheckFailed:
        return QStringLiteral("Couldn't reach GitHub - check your connection");
    case UpdateService::State::Downloading:
        return QStringLiteral("Downloading...");
    case UpdateService::State::Verified:
        return QStringLiteral("Ready to install");
    case UpdateService::State::DownloadFailed:
        // D-08 terminal copy - same wording the auto-path toast uses.
        return QStringLiteral("Update download failed - will try again tomorrow");
    }
    return QStringLiteral("Not checked yet");
}

bool SettingsWindow::updatesAutoInstall() const
{
    return m_settingsStore ? m_settingsStore->updatesAutoInstall() : false;
}

void SettingsWindow::setUpdatesAutoInstall(bool on)
{
    if (!m_settingsStore)
        return;
    m_settingsStore->setUpdatesAutoInstall(on);
    emit updateStatusChanged(); // toggle sub-line re-evaluates too
}

void SettingsWindow::checkForUpdatesNow()
{
    if (m_updates)
        m_updates->checkForUpdates(true); // manual button bypasses the daily guard
}

bool SettingsWindow::updateAvailable() const
{
    return m_updates && m_updates->state() == UpdateService::State::Available;
}

QString SettingsWindow::pendingVersion() const
{
    return updateAvailable() ? m_updates->availableVersion() : QString();
}

void SettingsWindow::downloadPendingUpdate()
{
    if (m_updates && m_updates->state() == UpdateService::State::Available)
        m_updates->downloadAndInstall();
}

void SettingsWindow::refreshScanState()
{
    // D-10 "state read when settings opens": live reads re-emitted so the
    // QML bindings re-resolve (SettingsWindow.h:52-53 precedent — no caching).
    emit scanRootsChanged();
    emit scanIntervalChanged();
    emit lastScanSummaryChanged();
}

void SettingsWindow::setFolderPicker(FolderPicker fn)
{
    m_folderPicker = std::move(fn);
}

void SettingsWindow::openHotkeyCapture()
{
    // HOTK-04: release the global combo while capturing (same reason as the
    // tray handoff in main.cpp) — resume() on accept/cancel re-arms it.
    m_hotkeys->suspend();
    if (m_capture)
        m_capture->open(currentHotkey());
}

void SettingsWindow::openColorDialog()
{
    if (!m_colorDialog) {
        // 2026-08-12: module-import load (see ensureWindow) — the hardcoded
        // qrc URL could never resolve (module resources live under the qml/
        // subdir), silently killing the Custom… color path.
        QQmlComponent component(m_engine);
        component.setData("import wisp\nColorDialog {\n}",
                          QUrl(QStringLiteral("qrc:/qt/qml/wisp/ColorDialog.qml")));
        if (!component.isReady()) {
            for (const auto &e : component.errors())
                qWarning() << e.toString();
            return;
        }
        // Per-instance host injection — same pattern as the settings window
        // itself and the capture dialog (no global context pollution).
        QObject *dialogObj = component.beginCreate(m_engine->rootContext());
        dialogObj->setProperty("settingsController", QVariant::fromValue(this));
        component.completeCreate();
        m_colorDialog = qobject_cast<QQuickWindow *>(dialogObj);
        if (!m_colorDialog)
            return;
    }
    // Auto-centered on open (D-02 geometry contract, capture-dialog logic).
    centerOnPrimary(m_colorDialog);
    m_colorDialog->show();
    m_colorDialog->requestActivate();
}

bool SettingsWindow::eventFilter(QObject *watched, QEvent *event)
{
    // Esc → close (D-02 dismissal; QML surface has no key handler — the
    // controller owns it per 06-02 contract).
    if (watched == m_window && event->type() == QEvent::KeyPress) {
        auto *ke = static_cast<QKeyEvent *>(event);
        if (ke->key() == Qt::Key_Escape && !ke->isAutoRepeat()) {
            close();
            return true;
        }
    }
    return QObject::eventFilter(watched, event);
}

QQuickWindow *SettingsWindow::ensureWindow()
{
    if (m_window)
        return m_window;

    // 2026-08-12 (found by tst_shell::settingsWindowContract): the hardcoded
    // qrc URL could NEVER resolve — qt_add_qml_module keeps the QML_FILES'
    // qml/ subdir under the QTP0001 prefix, so the real path is
    // :/qt/qml/wisp/qml/SettingsWindow.qml. The load failed silently
    // (qWarning only) and the tray Settings entry appeared dead — the phase-06
    // "token-only" verification never opened the window. Load through the
    // MODULE import system instead (engine.loadFromModule parity): the
    // qmldir maps the type name to the real path, no literal URL to rot.
    QQmlComponent component(m_engine);
    component.setData("import wisp\nSettingsWindow {\n}",
                      QUrl(QStringLiteral("qrc:/qt/qml/wisp/SettingsWindow.qml")));
    if (!component.isReady()) {
        for (const auto &e : component.errors())
            qWarning() << e.toString();
        return nullptr;
    }
    // Host injection: SettingsWindow.qml declares
    // `readonly property var settingsController: null` and null-guards every
    // call — bindings re-resolve once the controller is set.
    QObject *winObj = component.beginCreate(m_engine->rootContext());
    winObj->setProperty("settingsController", QVariant::fromValue(this));
    component.completeCreate();
    m_window = qobject_cast<QQuickWindow *>(winObj);
    if (!m_window)
        return nullptr;

    m_window->installEventFilter(this); // Esc → close()

    // Click-away (D-02.4 pattern): deactivation starts the 150ms grace;
    // re-activation of the settings window itself cancels it. The grace
    // arms ONLY after the first activation (2026-08-12 open-race fix): the
    // show → tray-menu-close/focus-handoff sequence can produce a transient
    // activeChanged(false) before the window ever activates — arming the
    // timer there closes a freshly opened window 150ms later. Before the
    // first activation, a deactivation is just the open race: ignore it.
    connect(m_window, &QQuickWindow::activeChanged, this, [this] {
        if (!m_window)
            return;
        if (m_window->isActive()) {
            m_hasBeenActive = true;
            m_graceTimer->stop();
        } else if (m_hasBeenActive) {
            startGraceTimer();
        }
    });

    // 120ms fade-in on open (Theme.animFade; UI-SPEC Animation contract).
    m_fade = new QPropertyAnimation(m_window, "opacity", this);
    m_fade->setDuration(kFadeMs);
    m_fade->setStartValue(0.0);
    m_fade->setEndValue(1.0);
    m_fade->setEasingCurve(QEasingCurve::Linear);

    // 2026-08-15: 120ms fade-out on close (mirror of the open fade). The
    // window hides on finished — the emission of settingsVisibleChanged
    // happens there too (hideWindow), so the surface never reports visible
    // while mid-fade.
    m_closeFade = new QPropertyAnimation(m_window, "opacity", this);
    m_closeFade->setDuration(kFadeMs);
    m_closeFade->setStartValue(1.0);
    m_closeFade->setEndValue(0.0);
    m_closeFade->setEasingCurve(QEasingCurve::Linear);
    connect(m_closeFade, &QPropertyAnimation::finished, this,
            &SettingsWindow::hideWindow);

    return m_window;
}

void SettingsWindow::centerOnPrimary(QQuickWindow *win)
{
    // Same centerOnScreen logic as MainWindow — re-applied EVERY show
    // (UI-SPEC Geometry contract).
    if (QScreen *screen = QGuiApplication::primaryScreen()) {
        const QRect avail = screen->availableGeometry();
        win->setX(avail.x() + (avail.width() - win->width()) / 2);
        win->setY(avail.y() + (avail.height() - win->height()) / 2);
    }
}

void SettingsWindow::startGraceTimer()
{
    m_graceTimer->start();
}

void SettingsWindow::onGraceTimeout()
{
    if (!m_window || !m_window->isVisible())
        return;

    // RESEARCH Pitfall 4 / D-04: if the newly-active window is one of OUR
    // OWN (launcher pop-over, modal color dialog), settings stays open.
    if (anotherOfOurWindowsIsActive())
        return;

    close();
}

bool SettingsWindow::anotherOfOurWindowsIsActive() const
{
    // QGuiApplication::focusWindow() alone is unreliable here: it goes null
    // the moment a FOREIGN window takes activation, while the launcher/color
    // dialog — our own QWindows — keep isActive() true. Checking our own
    // top-level windows covers both sides of the exemption (A4).
    for (QWindow *w : QGuiApplication::topLevelWindows()) {
        if (w == m_window)
            continue; // the settings window itself is inactive by definition here
        if (w->isActive())
            return true;
    }
    // The staged ColorDialog is ApplicationModal — belt and braces: a modal
    // window of ours keeps the app-surface context alive even on platforms
    // where the active-window bookkeeping lags.
    if (QWindow *modal = QGuiApplication::modalWindow())
        if (modal != m_window)
            return true;
    return false;
}
