#include "ui/SettingsWindow.h"

#include <QEvent>
#include <QGuiApplication>
#include <QKeyEvent>
#include <QPropertyAnimation>
#include <QQmlComponent>
#include <QQmlEngine>
#include <QQuickItem>
#include <QQuickWindow>
#include <QScreen>
#include <QTimer>

#include "core/AutostartManager.h"
#include "core/HotkeyManager.h"
#include "core/SettingsStore.h"
#include "ui/HotkeyCaptureDialog.h"

namespace {

// D-02: click-away grace (launcher's D-02.4 pattern) and the UI-SPEC
// 120ms open fade (Theme.animFade).
constexpr int kGraceMs = 150;
constexpr int kFadeMs = 120;

} // namespace

SettingsWindow::SettingsWindow(QQmlEngine *engine, SettingsStore *settingsStore,
                               AutostartManager *autostart, HotkeyManager *hotkeys,
                               HotkeyCaptureDialog *capture, QObject *parent)
    : QObject(parent)
    , m_engine(engine)
    , m_settingsStore(settingsStore)
    , m_autostart(autostart)
    , m_hotkeys(hotkeys)
    , m_capture(capture)
{
    // Hotkey-row handoff (D-03, success criterion 3): the EXISTING capture
    // dialog validates (F12/mod-only rejected) and surfaces conflicts via its
    // shipped balloon path — the controller only re-registers on accept.
    // setHotkey persists + atomically swaps (HOTK-01); on OS conflict the old
    // combo stays registered and registrationFailed fires (never silent).
    connect(m_capture, &HotkeyCaptureDialog::accepted, this,
            [this](const QString &seq) {
                m_hotkeys->setHotkey(QKeySequence(seq));
                emit currentHotkeyChanged(); // live well text (QML binding)
            });

    m_graceTimer = new QTimer(this);
    m_graceTimer->setSingleShot(true);
    m_graceTimer->setInterval(kGraceMs);
    connect(m_graceTimer, &QTimer::timeout, this, &SettingsWindow::onGraceTimeout);
}

void SettingsWindow::open()
{
    QQuickWindow *win = ensureWindow();
    if (!win)
        return;

    // D-10: state is read when settings opens (and after every mutation).
    emit autostartEnabledChanged();
    emit currentHotkeyChanged();

    // UI-SPEC open sequence: center → fade-in (120ms) → requestActivate.
    centerOnPrimary(win);
    win->setOpacity(0.0);
    win->show();
    if (m_fade)
        m_fade->start();
    win->requestActivate();
    // First focus on the hotkey row = first Tab stop (UI-SPEC Interaction
    // Contract + Keyboard row: hotkey well → strip → Custom… → toggle).
    if (QQuickItem *content = win->contentItem())
        content->forceActiveFocus();
    emit settingsVisibleChanged(true);
}

void SettingsWindow::close()
{
    m_graceTimer->stop();
    m_hasBeenActive = false; // the next open re-arms the grace on ITS first activation
    if (m_fade)
        m_fade->stop();
    if (m_window) {
        m_window->setOpacity(1.0); // reset — the next open fades from 0 again
        m_window->hide();          // instant — no close animation (UI-SPEC)
        emit settingsVisibleChanged(false);
    }
}

QString SettingsWindow::currentHotkey() const
{
    return m_hotkeys ? m_hotkeys->hotkey().toString() : QString();
}

bool SettingsWindow::autostartEnabled() const
{
    return m_autostart && m_autostart->isEnabled();
}

void SettingsWindow::applyAccent(const QColor &c)
{
    // D-06 path: persist + live apply. Invalid colors are silently ignored
    // downstream (SettingsStore, D-16).
    if (m_settingsStore)
        m_settingsStore->setAccent(c);
}

void SettingsWindow::commitCustomColor(const QString &hex)
{
    // T-06-01: the hex string is GENERATED by the staged dialog (never
    // freeform input); an invalid value is silently ignored (D-16).
    QColor c;
    c.setNamedColor(hex);
    if (!c.isValid())
        return;
    applyAccent(c);
}

void SettingsWindow::toggleAutostart()
{
    if (!m_autostart)
        return;
    m_autostart->setEnabled(!m_autostart->isEnabled());
    // The toggle reflects the operation's OUTCOME (UI-SPEC): the property
    // getter reads the store live, so a failed write stays visually off.
    emit autostartEnabledChanged();
}

void SettingsWindow::openHotkeyCapture()
{
    if (m_capture)
        m_capture->open(currentHotkey());
}

void SettingsWindow::openColorDialog()
{
    if (!m_colorDialog) {
        // 2026-08-12: module-import load (see ensureWindow) — the hardcoded
        // qrc URL could never resolve (module resources live under the qml/
        // subdir), silently killing the Custom… color path.
        QQmlComponent component(m_engine);
        component.setData("import wisp\nColorDialog {\n}",
                          QUrl(QStringLiteral("qrc:/qt/qml/wisp/ColorDialog.qml")));
        if (!component.isReady()) {
            for (const auto &e : component.errors())
                qWarning() << e.toString();
            return;
        }
        // Per-instance host injection — same pattern as the settings window
        // itself and the capture dialog (no global context pollution).
        QObject *dialogObj = component.beginCreate(m_engine->rootContext());
        dialogObj->setProperty("settingsController", QVariant::fromValue(this));
        component.completeCreate();
        m_colorDialog = qobject_cast<QQuickWindow *>(dialogObj);
        if (!m_colorDialog)
            return;
    }
    // Auto-centered on open (D-02 geometry contract, capture-dialog logic).
    centerOnPrimary(m_colorDialog);
    m_colorDialog->show();
    m_colorDialog->requestActivate();
}

bool SettingsWindow::eventFilter(QObject *watched, QEvent *event)
{
    // Esc → close (D-02 dismissal; QML surface has no key handler — the
    // controller owns it per 06-02 contract).
    if (watched == m_window && event->type() == QEvent::KeyPress) {
        auto *ke = static_cast<QKeyEvent *>(event);
        if (ke->key() == Qt::Key_Escape && !ke->isAutoRepeat()) {
            close();
            return true;
        }
    }
    return QObject::eventFilter(watched, event);
}

QQuickWindow *SettingsWindow::ensureWindow()
{
    if (m_window)
        return m_window;

    // 2026-08-12 (found by tst_shell::settingsWindowContract): the hardcoded
    // qrc URL could NEVER resolve — qt_add_qml_module keeps the QML_FILES'
    // qml/ subdir under the QTP0001 prefix, so the real path is
    // :/qt/qml/wisp/qml/SettingsWindow.qml. The load failed silently
    // (qWarning only) and the tray Settings entry appeared dead — the phase-06
    // "token-only" verification never opened the window. Load through the
    // MODULE import system instead (engine.loadFromModule parity): the
    // qmldir maps the type name to the real path, no literal URL to rot.
    QQmlComponent component(m_engine);
    component.setData("import wisp\nSettingsWindow {\n}",
                      QUrl(QStringLiteral("qrc:/qt/qml/wisp/SettingsWindow.qml")));
    if (!component.isReady()) {
        for (const auto &e : component.errors())
            qWarning() << e.toString();
        return nullptr;
    }
    // Host injection: SettingsWindow.qml declares
    // `readonly property var settingsController: null` and null-guards every
    // call — bindings re-resolve once the controller is set.
    QObject *winObj = component.beginCreate(m_engine->rootContext());
    winObj->setProperty("settingsController", QVariant::fromValue(this));
    component.completeCreate();
    m_window = qobject_cast<QQuickWindow *>(winObj);
    if (!m_window)
        return nullptr;

    m_window->installEventFilter(this); // Esc → close()

    // Click-away (D-02.4 pattern): deactivation starts the 150ms grace;
    // re-activation of the settings window itself cancels it. The grace
    // arms ONLY after the first activation (2026-08-12 open-race fix): the
    // show → tray-menu-close/focus-handoff sequence can produce a transient
    // activeChanged(false) before the window ever activates — arming the
    // timer there closes a freshly opened window 150ms later. Before the
    // first activation, a deactivation is just the open race: ignore it.
    connect(m_window, &QQuickWindow::activeChanged, this, [this] {
        if (!m_window)
            return;
        if (m_window->isActive()) {
            m_hasBeenActive = true;
            m_graceTimer->stop();
        } else if (m_hasBeenActive) {
            startGraceTimer();
        }
    });

    // 120ms fade-in on open (Theme.animFade; UI-SPEC Animation contract).
    m_fade = new QPropertyAnimation(m_window, "opacity", this);
    m_fade->setDuration(kFadeMs);
    m_fade->setStartValue(0.0);
    m_fade->setEndValue(1.0);
    m_fade->setEasingCurve(QEasingCurve::Linear);

    return m_window;
}

void SettingsWindow::centerOnPrimary(QQuickWindow *win)
{
    // Same centerOnScreen logic as MainWindow — re-applied EVERY show
    // (UI-SPEC Geometry contract).
    if (QScreen *screen = QGuiApplication::primaryScreen()) {
        const QRect avail = screen->availableGeometry();
        win->setX(avail.x() + (avail.width() - win->width()) / 2);
        win->setY(avail.y() + (avail.height() - win->height()) / 2);
    }
}

void SettingsWindow::startGraceTimer()
{
    m_graceTimer->start();
}

void SettingsWindow::onGraceTimeout()
{
    if (!m_window || !m_window->isVisible())
        return;

    // RESEARCH Pitfall 4 / D-04: if the newly-active window is one of OUR
    // OWN (launcher pop-over, modal color dialog), settings stays open.
    if (anotherOfOurWindowsIsActive())
        return;

    close();
}

bool SettingsWindow::anotherOfOurWindowsIsActive() const
{
    // QGuiApplication::focusWindow() alone is unreliable here: it goes null
    // the moment a FOREIGN window takes activation, while the launcher/color
    // dialog — our own QWindows — keep isActive() true. Checking our own
    // top-level windows covers both sides of the exemption (A4).
    for (QWindow *w : QGuiApplication::topLevelWindows()) {
        if (w == m_window)
            continue; // the settings window itself is inactive by definition here
        if (w->isActive())
            return true;
    }
    // The staged ColorDialog is ApplicationModal — belt and braces: a modal
    // window of ours keeps the app-surface context alive even on platforms
    // where the active-window bookkeeping lags.
    if (QWindow *modal = QGuiApplication::modalWindow())
        if (modal != m_window)
            return true;
    return false;
}
